drop database erizosCF;
create database erizosCF;

use erizosCF;
drop table usuarios;

CREATE TABLE usuarios (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cuenta_cf VARCHAR(100) NOT NULL,
    nombre VARCHAR(100),
    apellido_paterno VARCHAR(100),
    estado VARCHAR(100),
    genero VARCHAR(50),
    tipo VARCHAR(50),
    curso_actual INT NOT NULL DEFAULT 1,
    activo TINYINT(1) DEFAULT 1
);

INSERT INTO usuarios (
    cuenta_cf,
    nombre,
    apellido_paterno,
    estado,
    genero,
    tipo,
    curso_actual,
    activo
) VALUES
('Roberth_G', 'Roberth', 'G', 'ICPC', 'M', 'ITSUR', 3, 1),
('1ANH6', 'ANH6', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('gerogeVT', 'George', 'VT', 'ICPC', 'M', 'ITSUR', 3, 1),
('Cerritos', 'Cerritos', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('NeymarJR10', 'Neymar', 'JR', 'ICPC', 'M', 'ITSUR', 3, 1),
('leneza_41', 'Leneza', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('Alan078', 'Alan', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('KarlaBelenF', 'Karla Belen', '', 'ICPC', 'F', 'ITSUR', 3, 1),
('JuanPa', 'JuanPa', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('Sam3', 'Sam', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('DiegoCraftssj2', 'Diego', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Jab0n', 'Jabon', '', 'NORMAL', 'M', 'ITSUR', 3, 1),
('AdrianRN', 'Adrian', 'RN', 'NORMAL', 'M', 'ITSUR', 2, 1),
('MarioPrz3', 'Mario', 'Prz', 'NORMAL', 'M', 'ITSUR', 3, 1),
('Juan79', 'Juan', '', 'NORMAL', 'M', 'ITSUR', 3, 0),
('Giostef', 'Giostef', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('mzz2', 'Mzz', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Osva_D4C', 'Osva', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Angeldio', 'Angel', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('pato_coder', 'Pato', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Arrow912', 'Arrow', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('KikinJacob', 'Jacob', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('sggutier', 'Saul', 'Gutierrez', 'ICPC', 'M', 'EXTERNO', 3, 1),
('OrlandoIsay', 'Orlando', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('roadToWorldFinals9', 'Tilin', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('MarioJimenez9', 'Mario', 'Jimenez', 'NORMAL', 'M', 'EXTERNO', 3, 1),
('Karyme_Nava', 'Karyme', 'Nava', 'ICPC', 'F', 'EXTERNO', 3, 1),
('Thanya_Leif', 'Thanya', '', 'NORMAL', 'F', 'ITSUR', 2, 1),
('licgerman', 'Licgerman', '', 'RIESGO', 'M', 'EXTERNO', 3, 1),
('Jorge_Medina', 'Jorge', 'Medina', 'NORMAL', 'M', 'ITSUR', 2, 1),
('AuroraPrz1809', 'Aurora', 'Prz', 'NORMAL', 'F', 'EXTERNO', 3, 1),
('EllPanda', 'Ell', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Melecichu', 'Melecichu', '', 'NORMAL', 'F', 'ITSUR', 2, 1),
('AlexQA', 'Alex', '', 'ICPC', 'M', 'ITSUR', 3, 1),
('Andros_', 'Andros', '', 'ICPC', 'M', 'EXTERNO', 3, 1),
('ElPedrangas03', 'Pedro', '', 'ICPC', 'M', 'EXTERNO', 3, 1),
('Ismael101038', 'Ismael', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Mafer111111112', 'Mafer', '', 'RIESGO', 'F', 'EXTERNO', 2, 1),
('Al_Lopez', 'Al', 'Lopez', 'NORMAL', 'M', 'ITSUR', 2, 1),
('diego_ramirez_097', 'Diego', 'Ramirez', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Gabo_03', 'Gabriel', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('ArturoDiazZamudio', 'Arturo', 'Diaz', 'NORMAL', 'M', 'ITSUR', 2, 1),
('luis8', 'Luis', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Antoniopr', 'Antonio', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Smitty', 'Smitty', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('yisusrgg', 'Yisus', 'Rosiles', 'NORMAL', 'M', 'ITSUR', 2, 1),
('C4rlosVz', 'Carlos', 'V', 'NORMAL', 'M', 'ITSUR', 2, 1),
('scg1004', 'SCG', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('leo25', 'Leo', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('ulisesjared', 'Ulises', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Salgado29', 'Salgado', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('alexia_martinez', 'Alexia', 'Martinez', 'NORMAL', 'F', 'ITSUR', 2, 1),
('AndyPaola', 'Andy Paola', '', 'NORMAL', 'F', 'ITSUR', 2, 1),
('MikeMR', 'Mike', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Are_You_The_Cookie', 'Cookie', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('DT3264', 'DT', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('nitstalkr', 'Nitstalkr', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('LeRougeOiseau', 'LeRouge', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('arq.edu345', 'Arq', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('CristianToZa', 'Cristian', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('ISCHGMZ02', 'ISCHGMZ', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Cesar26', 'Cesar', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Daniel945', 'Daniel', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('EduardoR10', 'Eduardo', 'R', 'NORMAL', 'M', 'ITSUR', 2, 1),
('lgrifyee', 'Lgrifyee', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Davidavid', 'David', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('betoxx', 'Beto', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Lizet529', 'Lizet', '', 'NORMAL', 'F', 'ITSUR', 2, 1),
('Elizabeth_lml', 'Elizabeth', '', 'NORMAL', 'F', 'ITSUR', 2, 1),
('FredyGarcia', 'Fredy', 'Garcia', 'NORMAL', 'M', 'ITSUR', 2, 1),
('thedarkmonster06', 'DarkMonster', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('jorgeguc', 'Jorge', '', 'NORMAL', 'M', 'ITSUR', 2, 1),
('Axents', 'Axents', '', 'NORMAL', 'M', 'ITSUR', 2, 1);